# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroupProject
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  
  target 'GroupProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
